### ISSUE TITLE
如何注释

### ISSUE THREAD

**Issue by PeterPanwl** [PeterPanwl/SAC_FORTRAN_interface#40]
添加注释，我目前的想法：
1.用英语
2.主程序内的注释：
        1说明主程序内的变量含义，传入子程序的那些变量除外
        2程序各部分在干什么
        3强调use sacio等必须使用的语句
        4保留编译方法
3子程序内的注释：
        1说明变量含义，如何使用
        2子程序各部分在干什么，只说在干什么，不说怎么干的
4readme：
        1留下我们的邮箱

**Comment by seisman** [comment]
1. OK
2. 主程序需要重新整理，对各个子程序的测试需要独立开来
2.1 很多变量都没必要说明，比如i、filename等等
2.2 OK
2.3 有Fortran基础的人都应该懂的问题就不用说了
2.4 编译方法是应该放在main还是放在sacio.f95？README里也放一份
3. 
3.1 变量含义已经算写好了吧
3.2 可以，但是很多时候是不必要的，比如在open语句前写注释“open file”就完全没必要
4. OK

**Comment by PeterPanwl** [comment]
子程序的测试相互独立是什么意思？是要前面的完全不影响后面吗？

**Comment by seisman** [comment]
是，其实最理想的方式是写多个主程序，分别展示不同子程序的用法。在SAC手册中，C语言 的SAC I/O的示例就是这样做的，你可以看看那一节的目录，每一小节有一个子程序，展示不同的用法。

**Comment by seisman** [comment]
另外，`sacio_readhead_alpha`这个子程序其实有些多余，如果要考虑alpha文件的话，则所有子程序都需要写两套，一套处理binary，一套处理alpha。

而alpha平时其实很少用到，所以还不如把这唯一的alpha给删除

**Comment by PeterPanwl** [comment]
把sacio_readhead_alpha留着，以后闲了，再写alpha那一套，打发时间
多个主程序：先改sacio的注释，再写多个主程序。
注释那些：我先来写，然后你来看

**Comment by seisman** [comment]
写多个主程序的另外一个好处在于，写完之后就可以直接把这些代码放到SAC手册中了

**Comment by PeterPanwl** [comment]
恩，会写的
